name: Notificar Família

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  chamar-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Instalar navegadores do Playwright
        run: npx playwright install --with-deps chromium

      - name: Rodar notificação
        run: node notificar.js
